const description = [
    'Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their',
    'tiny stature, and even others for their massive size.',
  ].join(' ')
const data = [
    {
        title:"Maruthi Swift Desire",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/swift.png",
        category:"4 Wheelers",
        purpose:"S",
        brand:"Maruthi",
        model:"Desire",
        year:"2004",
        price:"1000",
        location:"Koramangala",
        phone:"554554",
        postTimestamp:"Thu Aug 31 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    },
    {
        title:"Bugatti Chevr",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/super-cars.png",
        category:"4 Wheelers",
        purpose:"S",
        brand:"Bugatti",
        model:"Chevr",
        year:"2012",
        price:"1000000",
        location:"Koramangala",
        phone:"55455ff4",
        postTimestamp:"Thu Aug 25 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    },
    {
        title:"iPhone 7",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/iphone.jpg",
        category:"Electronics",
        brand:"Apple",
        purpose:"S",
        model:"iPhone 7",
        year:"2015",
        price:"100000",
        location:"Koramangala",
        phone:"554554",
        postTimestamp:"Thu Aug 26 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    },
    {
        title:"Bullet Desert Storm",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/bullet.png",
        category:"2 Wheelers",
        brand:"RE",
        model:"Deset Storm 500",
        purpose:"S",
        year:"2016",
        price:"200000",
        location:"Koramangala",
        phone:"554554",
        postTimestamp:"Thu Aug 28 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    },
    {
        title:"Need a partner for 2 sharing",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/share.jpg",
        category:"Real Estate",
        purpose:"SH",
        brand:"2 BHK",
        model:"2 sharing bedroom",
        location:"Marathahalli",
       
        year:"",
        price:"1000",
        phone:"554554",
        postTimestamp:"Thu Aug 30 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    },
    {
        title:"Rent a house - 3 BHK",
        ntId:"npsaa",
        email:"npsaa@allstate.com",
        image:"images/rent.jpeg",
        category:"Real Estate",
        purpose:"R",
        brand:"3 BHK",
        model:"",
        location:"Koramangala",
        
        year:"",
        price:"1000",
        phone:"554554",
        postTimestamp:"Thu Aug 29 2017 19:03:35 GMT+0530 (IST)",
        deletionFlag:false,
        description:description
    }
]

export default data;